apiVersion: v1
kind: Namespace
metadata:
  name: learnware
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: learnware-backend
  namespace: learnware
  labels:
    app: learnware-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learnware-backend
  template:
    metadata:
      labels:
        app: learnware-backend
    spec:
      containers:
      - name: learnware-backend
        image: {{IMAGE_NAME}}
        imagePullPolicy: Always
        ports:
        - containerPort: {{PORT}}
---
apiVersion: v1
kind: Service
metadata:
  name: learnware-backend
  namespace: learnware
spec:
  type: NodePort
  selector:
    app: learnware-backend
  ports:
    - port: {{PORT}}
      targetPort: {{PORT}}
      nodePort: 30008
---
apiVersion: v1
kind: Service
metadata:
  name: learnware-backend-cluster
  namespace: learnware
spec:
  type: ClusterIP
  selector:
    app: learnware-backend
  ports:
    - port: {{PORT}}
      targetPort: {{PORT}}