apiVersion: v1
kind: Namespace
metadata:
  name: learnware
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: learnware-admin-frontend
  namespace: learnware
  labels:
    app: learnware-admin-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learnware-admin-frontend
  template:
    metadata:
      labels:
        app: learnware-admin-frontend
    spec:
      containers:
      - name: learnware-admin-frontend
        image: {{IMAGE_NAME}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{PORT}}
---
apiVersion: v1
kind: Service
metadata:
  name: learnware-admin-frontend
  namespace: learnware
spec:
  type: NodePort
  selector:
    app: learnware-admin-frontend
  ports:
    - port: {{PORT}}
      targetPort: {{PORT}}
      nodePort: 30009