name: trigger jenkins job
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: trigger deploy Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://39.100.108.32:7101/"
        user: "auto_deploy"
        token: 11480f0579eaf63b2f83b3df3fae1c9040
        job: "auto_deploy/BM-System-Backend-prd"
